# Generated by Django 4.0.6 on 2022-07-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paycheckName', models.CharField(max_length=255)),
                ('paycheckDate', models.CharField(max_length=255)),
                ('paycheckAmmount', models.IntegerField()),
            ],
        ),
    ]
