# Generated by Django 4.0.6 on 2022-08-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='BILL', max_length=20)),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=20)),
                ('ammount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ammount_in_bank', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bills_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date', models.DateField()),
                ('bills', models.ManyToManyField(blank=True, to='finances.bill')),
            ],
        ),
    ]
