# Generated by Django 4.0.6 on 2022-07-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ammount', models.IntegerField()),
                ('dueDate', models.CharField(max_length=255)),
            ],
        ),
    ]
