# Generated by Django 4.0.6 on 2022-07-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_rename_paycheckammount_paycheck_ammount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='bills',
            field=models.ManyToManyField(to='finances.bill'),
        ),
    ]
