# Generated by Django 4.0.6 on 2022-07-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_paycheck_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='bills',
            field=models.ManyToManyField(related_name='bills', to='finances.bill'),
        ),
    ]
