# Generated by Django 4.0.6 on 2022-07-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_paycheck_bills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='dueDate',
            new_name='due_date',
        ),
    ]
