# Generated by Django 4.0.6 on 2022-07-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_alter_bill_id_alter_paycheck_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='money_in_bank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
