# Generated by Django 4.0.6 on 2022-07-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_bill_money_in_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paycheck',
            old_name='ammount',
            new_name='ammount_in_bank',
        ),
    ]
