# Generated by Django 4.0.6 on 2022-07-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_rename_ammount_paycheck_ammount_in_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='ammount_in_bank',
            field=models.IntegerField(blank=True),
        ),
    ]
