# Generated by Django 4.0.6 on 2022-07-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_remove_bill_money_in_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='bills',
            field=models.ManyToManyField(null=True, to='finances.bill'),
        ),
    ]
