# Generated by Django 4.0.6 on 2022-07-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_alter_paycheck_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='ammount_in_bank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='bills',
            field=models.ManyToManyField(blank=True, to='finances.bill'),
        ),
    ]
