# Generated by Django 4.0.6 on 2022-07-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_alter_paycheck_ammount_in_bank_alter_paycheck_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
