# Generated by Django 4.0.6 on 2022-07-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0017_alter_bill_due_date_alter_paycheck_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='date',
            field=models.DateField(),
        ),
    ]
