# Generated by Django 4.0.6 on 2022-07-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0018_alter_bill_due_date_alter_paycheck_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='ammount',
            field=models.IntegerField(null=True),
        ),
    ]
