# Generated by Django 4.0.6 on 2022-08-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_paycheck_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billsTotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
