# Generated by Django 4.0.6 on 2022-08-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0020_bill_billstotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='billsTotal',
        ),
        migrations.AddField(
            model_name='paycheck',
            name='billsTotal',
            field=models.IntegerField(default=0),
        ),
    ]
