# Generated by Django 4.0.6 on 2022-08-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0021_remove_bill_billstotal_paycheck_billstotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paycheck',
            old_name='billsTotal',
            new_name='bills_total',
        ),
    ]
