# Generated by Django 4.0.6 on 2022-08-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0022_rename_billstotal_paycheck_bills_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='ballance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ammount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='ammount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='ammount_in_bank',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='bills_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
