# Generated by Django 4.0.6 on 2022-08-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0023_paycheck_ballance_alter_bill_ammount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paycheck',
            old_name='ballance',
            new_name='balance',
        ),
    ]
