# Generated by Django 4.0.6 on 2022-08-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0024_rename_ballance_paycheck_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='ammount_in_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
