# Generated by Django 4.0.6 on 2022-08-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0025_alter_paycheck_ammount_in_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
