# Generated by Django 4.0.6 on 2022-08-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0026_remove_bill_id_alter_bill_name_alter_paycheck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
