# Generated by Django 4.0.6 on 2022-08-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0028_remove_paycheck_bills_paycheck_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='bills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
