# Generated by Django 4.0.6 on 2022-08-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0031_alter_paycheck_bills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycheck',
            name='bills',
        ),
    ]
