# Generated by Django 4.0.6 on 2022-08-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0035_remove_paycheck_bills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycheck',
            name='ammount',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='ammount_in_bank',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='bills_total',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='date',
        ),
    ]
