# Generated by Django 4.0.6 on 2022-08-08 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0036_remove_paycheck_ammount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='ammount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='ammount_in_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='bills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finances.bill'),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='bills_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='name',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
