# Generated by Django 4.0.6 on 2022-08-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0037_paycheck_ammount_paycheck_ammount_in_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='bills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='finances.bill'),
        ),
    ]
