# Generated by Django 4.0.6 on 2022-08-08 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0039_alter_paycheck_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
