# Generated by Django 4.0.6 on 2022-08-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0040_alter_paycheck_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycheck',
            name='bills',
        ),
        migrations.AddField(
            model_name='paycheck',
            name='bills',
            field=models.ManyToManyField(blank=True, null=True, to='finances.bill'),
        ),
    ]
