# Generated by Django 4.0.6 on 2022-08-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0041_remove_paycheck_bills_paycheck_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='bills',
            field=models.ManyToManyField(blank=True, to='finances.bill'),
        ),
    ]
