# Generated by Django 4.0.6 on 2022-08-12 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0042_alter_paycheck_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(default='BILL', max_length=20),
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='bills',
        ),
        migrations.AddField(
            model_name='paycheck',
            name='bills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='finances.bill'),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
