# Generated by Django 4.0.6 on 2022-08-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0043_bill_id_alter_bill_name_remove_paycheck_bills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycheck',
            name='bills',
        ),
        migrations.AddField(
            model_name='paycheck',
            name='bills',
            field=models.ManyToManyField(blank=True, to='finances.bill'),
        ),
    ]
