# Generated by Django 4.0.6 on 2022-08-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_profile_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('phone_number', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
