# Generated by Django 4.0.6 on 2022-10-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='chore', max_length=20)),
                ('note', models.CharField(blank=True, default=0, max_length=20)),
                ('compleated', models.BooleanField(default=False)),
            ],
        ),
    ]
