# Generated by Django 4.0.6 on 2022-10-22 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_familymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedChores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_assigned', models.CharField(default='day', max_length=20)),
                ('chore_name', models.CharField(default='chore', max_length=20)),
                ('note', models.TextField(blank=True, max_length=80, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('parents_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('repeated_chore', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('chore_start_time', models.DateTimeField(blank=True, null=True)),
                ('chore_status', models.CharField(default='pending', max_length=20)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.familymember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_assigned', models.CharField(default='day', max_length=20)),
                ('chore_name', models.CharField(default='chore', max_length=20)),
                ('note', models.TextField(blank=True, max_length=80, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('parents_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('repeated_chore', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('chore_start_time', models.DateTimeField(blank=True, null=True)),
                ('chore_status', models.CharField(default='pending', max_length=20)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.familymember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
