# Generated by Django 4.0.6 on 2022-10-09 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_familymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore_name', models.CharField(default='chore', max_length=20)),
                ('note', models.CharField(blank=True, max_length=80, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('partents_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('repeated_chore', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('date_patrent_completed', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(blank=True, max_length=20)),
                ('chores', models.ManyToManyField(blank=True, to='chores.chore')),
            ],
        ),
    ]
