# Generated by Django 4.0.6 on 2022-10-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_rename_assigned_to_chore_assigned_tox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chore',
            old_name='assigned_tox',
            new_name='assigned_to',
        ),
    ]
