# Generated by Django 4.0.6 on 2022-10-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_rename_completedchores_chorelogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='chore_name',
            field=models.CharField(default='chore', max_length=100),
        ),
        migrations.AlterField(
            model_name='chore',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chorelogs',
            name='chore_name',
            field=models.CharField(default='chore', max_length=100),
        ),
        migrations.AlterField(
            model_name='chorelogs',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
