# Generated by Django 4.0.6 on 2022-10-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_rename_assigned_tox_chore_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
