# Generated by Django 4.0.6 on 2022-10-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_alter_chore_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
