# Generated by Django 4.0.6 on 2022-10-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_alter_chore_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='note',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
