# Generated by Django 4.0.6 on 2022-10-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0006_alter_chore_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='chore_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
