# Generated by Django 4.0.6 on 2022-10-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0007_chore_chore_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='chore_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='chore',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chore',
            name='partents_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chore',
            name='repeated_chore',
            field=models.BooleanField(default=False),
        ),
    ]
