# Generated by Django 4.0.6 on 2022-10-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0008_alter_chore_chore_status_alter_chore_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='date_patrent_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='partents_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='repeated_chore',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
