# Generated by Django 4.0.6 on 2022-10-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0009_alter_chore_completed_alter_chore_date_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chore',
            old_name='date_patrent_completed',
            new_name='date_parent_completed',
        ),
    ]
