# Generated by Django 4.0.6 on 2022-10-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0010_rename_date_patrent_completed_chore_date_parent_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chore',
            old_name='partents_completed',
            new_name='parents_completed',
        ),
    ]
