# Generated by Django 4.0.6 on 2022-10-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0011_rename_partents_completed_chore_parents_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='day_assigned',
            field=models.CharField(default='day', max_length=20),
        ),
    ]
