# Generated by Django 4.0.6 on 2022-08-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Item', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('itmes', models.ManyToManyField(blank=True, to='shopping_list.item')),
            ],
        ),
    ]
