# Generated by Django 4.0.6 on 2022-11-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_familymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Item', max_length=20)),
                ('note', models.CharField(blank=True, default=0, max_length=20)),
                ('requested_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=20)),
                ('note', models.CharField(blank=True, default=0, max_length=20)),
                ('items', models.ManyToManyField(blank=True, to='shopping_list.item')),
            ],
        ),
    ]
