# Generated by Django 4.0.6 on 2022-08-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='itmes',
            new_name='items',
        ),
    ]
