# Generated by Django 4.0.6 on 2022-08-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_rename_itmes_list_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
        migrations.RemoveField(
            model_name='list',
            name='date',
        ),
    ]
