# Generated by Django 4.0.6 on 2022-08-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_remove_item_date_remove_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='list',
            name='note',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
