# Generated by Django 4.0.6 on 2022-08-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_familymember'),
        ('shopping_list', '0004_alter_item_note_alter_list_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='requested_from',
            field=models.ManyToManyField(blank=True, to='accounts.familymember'),
        ),
    ]
