# Generated by Django 4.0.6 on 2022-08-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_familymember'),
        ('shopping_list', '0005_list_requested_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='requested_from',
        ),
        migrations.AddField(
            model_name='item',
            name='requested_from',
            field=models.ManyToManyField(blank=True, to='accounts.familymember'),
        ),
    ]
