# Generated by Django 4.0.6 on 2022-08-20 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_familymember'),
        ('shopping_list', '0006_remove_list_requested_from_item_requested_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='requested_from',
        ),
        migrations.AddField(
            model_name='item',
            name='requested_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.familymember'),
        ),
    ]
