version: '3.9'
services:
  # web:
  #   build: .
  #   command: python /hms/manage.py runserver 0.0.0.0:1234
  #   volumes:
  #     - .:/home/ravenstudios/hms
  #   ports:
  #     - 1234:1234

  web:
      build: .
      command: >
        "
         python manage.py migrate &&
         python manage.py runserver 0.0.0.0:1234
        "
      container_name: myproject_web
      # depends_on:
      #   - db
      # env_file:
      #   - .env
      ports:
        - "1234:1234"
      restart: unless-stopped
      volumes:
        - .:/home/ravenstudios/hms
