# Generated by Django 4.0.6 on 2022-08-21 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_familymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TITLE', max_length=200)),
                ('msg', models.CharField(blank=True, default='MESSAGE', max_length=200)),
                ('task_options', models.CharField(choices=[('Not Compleated', 'Not Compleated'), ('Compleated', 'Compleated'), ('Problem', 'Problem')], default='Not Compleated', max_length=20)),
                ('msg_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_author', to='accounts.familymember')),
                ('msg_recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_recipient', to='accounts.familymember')),
            ],
        ),
    ]
