# Generated by Django 4.0.6 on 2022-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='task_options',
            field=models.CharField(max_length=20),
        ),
    ]
