# Generated by Django 4.0.6 on 2022-08-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_time_created_message_time_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='comments',
            field=models.CharField(default='Comments', max_length=300),
        ),
    ]
